Feature/insights pages
nationalarchives/ds-wagtail-frontend pull request #5
Opened 2021-07-08 10:58 UTC by JamesWChan

Hi @gtvj,

This PR is for merging the Insights HTML components. The components I've added are:

 - Blog embed
 - Callout
 - Content block
 - Hero image
 - Jumplinks
 - Key facts (author)
 - Media embed (for audio and video)
 - Quote
 - Record embed w/ image
 - Record embed w/o image
 - Related content
 - Research resources
 - Section separator
 
It's quite a large PR so if you'd like to go through this together so I can answer any questions, just let me know. Thank you :+1

2021-07-12 10:06 UTC, gtvj reviewed
Just a note here: when integrating into `ds-wagtail` you'll probably need a different template for each path where you've included `if` statements within the template.

2021-07-12 10:06 UTC, gtvj commented on includes/blog-embed.php
> +    <p class="blog-embed__icon-label" role="presentation" aria-hidden="true">
I like the way you've tried to keep things as meaningful as possible for users of assistive technology with the use of `blog-embed__icon-label` - having it visually present but hidden from AT (so that it appears beneath the heading) and also including it later.

Rather than having it as a `<p>` tag within the content, I wonder if it might be better to prepend a `<span>` to  the `<h3>`, something like: 

```php
<h3 class="blog-embed__heading">
        <span class="sr-only"><?php echo $blog_embed_values['icon-label'] ?>: </span>
        <?php echo $blog_embed_values['heading'] ?>
</h3>
```

What are your thoughts on this?

2021-07-12 10:06 UTC, gtvj commented on includes/blog-embed.php
> +    <p class="blog-embed__icon-label sr-only" >
If we were to move this into the heading we could remove this `<p>` element

2021-07-12 10:06 UTC, gtvj commented on includes/callout.php
> +                        <div class="callout__list-item">
This is a note, rather than a comment on the PR to be addressed: while the MDN page says that `<div>` elements cannot be children of `<dl>`, the spec - which is linked to from the MDN page - does allow for this. See:  https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element

2021-07-12 10:06 UTC, gtvj commented on includes/callout.php
> +                                <h4 class="callout__link-heading">
Another confusing spec related issue. When run through the W3C validator, an error is raised on the basis that `<h4>` cannot be children of `<dt>`. This seems to be due to a difference between the WHATWG and W3C specs. It's not ideal that they're inconsistent but, for our purposes, I think we'll need to be aware that any strange behaviour -and I'm thinking especially inconsistent behaviour in user agents - might be due to this.

2021-07-12 10:06 UTC, gtvj commented on includes/media-embed__audio.php
> +        <p class="media-embed__icon-label sr-only" >
Similar to the comment above, I wonder if we could include this as a `<span class="sr-only">` to the `<h3>` rather the a stand-alone element. 

```php
    <h3 class="media-embed__heading">
        <span class="sr-only"><?php echo $audio_embed_values['icon-label'] ?>: </span>
        <?php echo $audio_embed_values['heading'] ?>
    </h3>
```

2021-07-12 10:26 UTC, gtvj requested changes
Hi @JamesWChan - really good work on this. I've made several comments but a lot of them are either general thoughts or to document that the choices you've made are justified. There are a few small changes I've requested too but I don't think they'll prove too onerous. Let me know if you'd like to chat about any part of this or if I can help in any way.

2021-07-12 10:26 UTC, gtvj commented on includes/media-embed__video.php
> +        <div class="media-embed__transcript">
This is a general note: when the `<audio>` and `<video>` embeds are integrated into `ds-wagtail` can the we put a note in for the developers to link to W3C guidance within the editorial interface. See: https://www.w3.org/WAI/WCAG21/Techniques/general/G159.html

2021-07-12 10:26 UTC, gtvj commented on sass/includes/_section-separator.scss
> +  left: calc(-50vw + 50%);
Just a general note: there are reported inconsistencies when using `calc()` in Internet Explorer. If you find that when testing in IE let me know because I found a good work-around for IE specific styles when working with CSS Grid.

2021-07-12 10:26 UTC, gtvj commented on sass/includes/_research-resources.scss
> +    font-size: 0.9em;
Could we change this to be `rem`

2021-07-12 10:26 UTC, gtvj commented on sass/includes/_record-embed__no-image.scss
> +    font-size: 0.9em;
Could we change this to be `rem`?

2021-07-12 10:26 UTC, gtvj commented on sass/includes/_media-embed.scss
> +    font-size: 0.9em;
Could we change this to be `rem`

2021-07-12 10:26 UTC, gtvj commented on sass/includes/_jumplinks.scss
> +@media only screen and (max-width: $screen__md)  {
I couldn't find the place where `column-count` is set to a different value. Because this is setting the count to 1, which is the default, I'm wondering if we might not need this media query (?). Let me know if I'm missing something.

2021-07-12 10:26 UTC, gtvj commented on includes/research-resources.php
> +    <p class="research-resources__icon-label sr-only" >
Similar to the comment for blog embed, if we were to put this as a `<span class="sr-only">` then we could avoid having this `<p>` tag

2021-07-13 08:33 UTC, JamesWChan commented on sass/includes/_section-separator.scss
> +  left: calc(-50vw + 50%);
Hi @gtvj,

I didn't notice any issues when testing in IE. I just checked again to make sure and everything seems to be working fine.

2021-07-13 09:34 UTC, gtvj approved these changes

2021-07-13 10:52 UTC, merged