Ds 218
nationalarchives/ds-wagtail-frontend pull request #8
Opened 2021-07-12 12:26 UTC by AshTNA

This contains changes from these designs by SW:

![image](https://user-images.githubusercontent.com/8880610/125286807-1ff60500-e314-11eb-9dda-a795788dd140.png)
![image](https://user-images.githubusercontent.com/8880610/125286821-23898c00-e314-11eb-8452-05d54b31ccb1.png)
![image](https://user-images.githubusercontent.com/8880610/125286837-26847c80-e314-11eb-8125-0be0e3f2e790.png)

2021-07-12 13:44 UTC, matt-blair commented on sass/includes/_results-options.scss
> +
Might be good to close the empty line here.

2021-07-12 13:47 UTC, matt-blair commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
Might need to add a media query to reduce left and right padding to match the content padding in the main container on smaller screen sizes. Currently different alignments,

2021-07-12 13:49 UTC, matt-blair commented on sass/includes/_generic_intro.scss
> +    }
Line-height or bottom margin needs increasing on mobile as it looks a bit tight against the larger heading size below on smaller screens.

2021-07-12 13:52 UTC, matt-blair commented on includes/header.php
> +    <p>
More an editorial question/comment (not sure if it's been looked over by a content designer) but I don't think we need Welcome to The National Archives. It's a bit redundant.

2021-07-12 13:53 UTC, matt-blair requested changes
Hi Ash, I've made a few single line comments which need resolving. Most are fairly straight-forward, one is more a question for Simon and the rest of the team about the strapline in the heading. (Not sure if the PR is the right place for it, but just thought it'd be worth checking before approving).

Matt.

2021-07-12 14:13 UTC, AshTNA commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
Thanks @matt-blair - i've realised that my header was completely different to Simon's design, so I have fixed it by wrapping it in a bootstrap container.

2021-07-12 14:13 UTC, AshTNA commented on sass/includes/_results-options.scss
> +
Done :+1:

2021-07-12 14:13 UTC, AshTNA commented on includes/header.php
> +    <p>
Thanks @matt-blair - I've been told that the heading is subject to change so there may be a different heading there so we can treat that as a placeholder.

2021-07-12 14:30 UTC, matt-blair commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
@AshTNA I think what you had before was right, just with a little less padding. We need the header to be full width rather than using a bootstrap container because the details page doesn't use container width for its main content area so there's an alignment issue. Making the header full width will mean it works across all 3 prototypes. I'd probably revert it back to what you had originally and then just change the padding-left and padding-right to 1rem rather than 3rem on mobile. That should do the job.

2021-07-12 15:21 UTC, AshTNA commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
Thanks @matt-blair - I see what you mean now, i've pushed the change. :+1:

2021-07-12 16:09 UTC, matt-blair commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
That's great. I think the bottom padding should probably change from 0rem to 1rem in the media query too as it causes a problem on mobile being quite tight against the generic-intro panel. Hopefully after that it'll be resolved.

2021-07-13 08:52 UTC, AshTNA commented on sass/includes/_header.scss
> +  padding: 1rem 3rem 0rem 3rem;
Thanks @matt-blair - I have updated this now too!

2021-07-13 08:54 UTC, AshTNA commented on sass/includes/_generic_intro.scss
> +    }
I've added a line-height of `line-height: 1.3em;` on mobile :+1:

2021-07-13 09:00 UTC, matt-blair commented on sass/includes/_generic_intro.scss
> +    }
Looks good!

2021-07-13 09:01 UTC, matt-blair approved these changes

2021-07-13 09:02 UTC, merged